
//Local Environment

GET http://localhost:3000/
###
GET http://localhost:3000/contacts/
###
GET http://localhost:3000/contacts/?id=63c23e6862102586f5c6444d 
###

//Render

GET https://cse341wintersword.onrender.com
###
GET https://cse341wintersword.onrender.com/contacts/
###
GET https://cse341wintersword.onrender.com/contacts/?id=63c23e6862102586f5c6444d
