GET http://localhost:3000/towns/
###
GET http://localhost:3000/inventory/
###
POST http://localhost:3000/towns/addTown/ HTTP/1.1
Content-Type: application/json

{
    "townName": "Testing",
    "population": "02",
    "description": "A development town.",
    "leader": "Developer",
    "climate": "Neutral",
    "specialty": "Void",
    "government": "Null"
}
###

POST http://localhost:3000/towns/addItem/ HTTP/1.1
Content-Type: application/json

{
    "name": "Testing",
    "description": "A void amulet.",
    "rarity": 101001,
    "equipment": "Necklace",
    "sell": "0x",
    "buy": "0xp"
}
###
PUT http://localhost:3000/towns/updateTown/?id=63e69da00b8a9b35930265f7 HTTP/1.1
Content-Type: application/json

{
    "townName": "Update",
    "population": "2",
    "description": "A updated town.",
    "leader": "Dev2",
    "climate": "Neutral2",
    "specialty": "Void2",
    "government": "Null2"
}
###
DELETE http://localhost:3000/towns/deleteTown/?id=63e69da00b8a9b35930265f7 HTTP/1.1
###
GET https://cse341wintersword.onrender.com/towns/
###
GET https://cse341wintersword.onrender.com/inventory/
###
POST https://cse341wintersword.onrender.com/towns/addTown/ HTTP/1.1
Content-Type: application/json

{
    "townName": "Testing",
    "population": "00001",
    "description": "A development town.",
    "leader": "Developer",
    "climate": "Neutral",
    "specialty": "Void",
    "government": "Null"
}
###
POST https://cse341wintersword.onrender.com/towns/addItem/ HTTP/1.1
Content-Type: application/json

{
    "name": "Testing",
    "description": "A void amulet.",
    "rarity": 101001,
    "equipment": "Necklace",
    "sell": "0x",
    "buy": "0xp"
}
###
PUT https://cse341wintersword.onrender.com/towns/updateTown/?id=63e696d64200bf2d83495b6d HTTP/1.1
Content-Type: application/json

{
    "townName": "Update",
    "population": "2",
    "description": "A updated town.",
    "leader": "Dev2",
    "climate": "Neutral2",
    "specialty": "Void2",
    "government": "Null2"
}
###
DELETE https://cse341wintersword.onrender.com/towns/deleteTown/?id=63e69797324f63a6d259597a HTTP/1.1
###